name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 30m
          script: |
            curl https://gist.githubusercontent.com/anonymax25/8566e982dfdbe4ae5e28dc89886dee4b/raw > docker-compose.yml
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d