export enum GameStatus {
    DICE_ROLLING = 'DICE_ROLLING',
    NUGGETS_RESULT = 'NUGGETS_RESULT',
    BANK_RESULT = 'BANK_RESULT',
    GENERAL_STORMS_RESULT = 'GENERAL_STORMS_RESULT',
    SALOON_RESULT = 'SALOON_RESULT',
    SHERIF_RESULTe = 'SHERIF_RESULTe',
    PROPERTY_RESULT = 'PROPERTY_RESULT',
    BAD_LUCK_RESULT = 'BAD_LUCK_RESULT',
}